GET http://localhost:5000/cakes

###
GET http://localhost:5000/cakes/1

###
POST http://localhost:5000/cakes
Content-Type: application/json

{
    "namaproduct": "Mini Brownies",
    "kategori": "Sweet Snacks",
    "harga": 5000,
    "stok": 20
}

###
PATCH  http://localhost:5000/cakes/1
Content-Type: application/json

{
    "namaproduct": "Mini Cakes",
    "kategori": "Cakes & Pastry",
    "harga": 17000,
    "stok": 20
}

###
DELETE http://localhost:5000/cakes/3


// soal 2
###
GET http://localhost:5000/cakes/search?kategori=Cakes%20%26%20Pastry&maxharga=25000


// soal 3
###
PATCH http://localhost:5000/cakes/1/stok
Content-Type: application/json

{
    "stok": 5
}
